
add_rules("mode.releasedbg")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})

target("shared")
    set_kind("static")
    set_encodings("utf-8")
    add_defines("UNICODE")
    add_files("src/shared/**.c", "src/shared/**.cpp")
    add_headerfiles("src/shared/**.h", "src/shared/**.hpp")
    add_includedirs("src/shared", {public = true})
    set_languages("c11", "cxx17")

target("cli")
    set_kind("binary")
    set_encodings("utf-8")
    add_defines("UNICODE")
    add_files("src/cli/**.c", "src/cli/**.cpp", "src/cli/**.rc", "src/cli/**.asm")
    add_headerfiles("src/cli/**.h", "src/cli/**.hpp")
    add_includedirs("src/cli", {public = true})
    add_deps("shared", "victim-drivers")
    set_languages("c11", "cxx17")
    add_syslinks("shell32", "advapi32")

target("helper-dll")
    set_kind("shared")
    set_encodings("utf-8")
    add_defines("UNICODE")
    add_files("src/helper-dll/**.c", "src/helper-dll/**.cpp", "src/helper-dll/**.def", "src/helper-dll/**.asm")
    add_headerfiles("src/helper-dll/**.h", "src/helper-dll/**.hpp")
    add_includedirs("src/helper-dll", {public = true})
    add_deps("shared")
    set_languages("c11", "cxx17")
    add_shflags("/NODEFAULTLIB:libucrt.lib", "/NODEFAULTLIB:libvcruntime.lib", {force = true})
    add_syslinks("shell32")

target("victim-drivers")
    set_kind("shared")
    set_encodings("utf-8")
    add_defines("UNICODE")
    add_files("src/victim-drivers/**.c", "src/victim-drivers/**.cpp", "src/victim-drivers/**.def", "src/victim-drivers/**.rc")
    add_headerfiles("src/victim-drivers/**.h", "src/victim-drivers/**.hpp")
    add_includedirs("src/victim-drivers", {public = true})
    add_deps("shared")
    set_languages("c11", "cxx17")

target("gen-asio-2-unlock")
    set_kind("binary")
    set_encodings("utf-8")
    add_defines("UNICODE")
    add_files("src/utils/gen-asio-2-unlock/**.c", "src/utils/gen-asio-2-unlock/**.cpp")
    add_headerfiles("src/utils/gen-asio-2-unlock/**.h", "src/utils/gen-asio-2-unlock/**.hpp")
    add_includedirs("src/utils/gen-asio-2-unlock", {public = true})
    set_languages("c11", "cxx17")
    add_deps("shared")
    add_syslinks("advapi32")

-- target("PCOMP")
--     set_kind("binary")
--     set_encodings("utf-8")
--     add_files("src/utils/PCOMP/**.c", "src/utils/PCOMP/**.cpp")
--     add_headerfiles("src/utils/PCOMP/**.h", "src/utils/PCOMP/**.hpp")
--     add_includedirs("src/utils/PCOMP", {public = true})
--     set_languages("c11", "cxx11")
--     add_deps("shared")