
add_rules("mode.releasedbg")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})
set_languages("cxx23")

add_requires("cxxopts", "boost_ut")

target("core")
    set_kind("static")
    set_encodings("utf-8")
    add_defines("UNICODE", "NOMINMAX")
    add_files("src/core/**.cc", "src/core/**.cpp")
    add_headerfiles("src/core/**.h")
    add_includedirs("src", {public = true})
    add_syslinks("advapi32")

local function add_provider_target(name)
    target(name .. "-provider")
        set_kind("static")
        set_encodings("utf-8")
        add_defines("UNICODE", "NOMINMAX")
        add_rules("utils.bin2obj", {extensions = {".bin"}})
        add_files("src/drivers/" .. name .. "/**.cpp")
        add_files("src/drivers/" .. name .. "/**.bin")
        add_deps("core")
        add_ldflags("/WHOLEARCHIVE:" .. name .. "-provider.lib", {force = true, public = true})
end

add_provider_target("mapmem")

target("test-lib")
    set_kind("static")
    set_encodings("utf-8")
    add_defines("UNICODE", "NOMINMAX")
    add_files("src/test-lib/**.cpp")
    add_headerfiles("src/test-lib/**.h")
    add_includedirs("src", {public = true})
    add_deps("core")
    set_languages("cxx23")

target("cli-new")
    set_kind("binary")
    set_encodings("utf-8")
    add_defines("UNICODE", "NOMINMAX")
    add_files("src/cli-new/**.cpp")
    add_headerfiles("src/cli-new/**.hpp", "src/cli-new/**.h")
    add_includedirs("src/cli-new", "src", {public = true})
    
    add_deps("core", "mapmem-provider", {public = true})
    add_deps("test-lib")
    set_languages("cxx23")
    add_syslinks("advapi32")
    add_packages("cxxopts", "boost_ut")

-- target("unit-test")
--     set_kind("binary")
--     set_encodings("utf-8")
--     add_defines("UNICODE", "NOMINMAX")
--     add_files("tests/unit_test.cpp")
--     add_includedirs("src", {public = true})
--     add_deps("core", "mapmem-provider", "test-lib", {public = true})
--     set_languages("cxx23")
--     add_syslinks("advapi32")
--     add_packages("boost_ut")

target("provider-tests")
    set_kind("binary")
    set_encodings("utf-8")
    add_defines("UNICODE", "NOMINMAX")
    add_files("tests/provider_tests.cpp")
    add_includedirs("src", {public = true})
    add_deps("core", "mapmem-provider", "test-lib")
    set_languages("cxx23")
    add_syslinks("advapi32")

target("shared")
    set_kind("static")
    set_encodings("utf-8")
    add_defines("UNICODE", "NOMINMAX")
    add_files("src/shared/**.c", "src/shared/**.cpp")
    add_headerfiles("src/shared/**.h", "src/shared/**.hpp")
    add_includedirs("src/shared", {public = true})
    set_languages("c11", "cxx17")

target("cli")
    set_kind("binary")
    set_encodings("utf-8")
    add_defines("UNICODE", "NOMINMAX")
    add_files("src/cli/**.c", "src/cli/**.cpp", "src/cli/**.rc", "src/cli/**.asm")
    add_headerfiles("src/cli/**.h", "src/cli/**.hpp")
    add_includedirs("src/cli", {public = true})
    add_deps("shared", "victim-drivers")
    set_languages("c11", "cxx17")
    add_syslinks("shell32", "advapi32")

target("helper-dll")
    set_kind("shared")
    set_encodings("utf-8")
    add_defines("UNICODE", "NOMINMAX")
    add_files("src/helper-dll/**.c", "src/helper-dll/**.cpp", "src/helper-dll/**.def", "src/helper-dll/**.asm")
    add_headerfiles("src/helper-dll/**.h", "src/helper-dll/**.hpp")
    add_includedirs("src/helper-dll", {public = true})
    add_deps("shared")
    set_languages("c11", "cxx17")
    add_shflags("/NODEFAULTLIB:libucrt.lib", "/NODEFAULTLIB:libvcruntime.lib", {force = true})
    add_syslinks("shell32")

target("victim-drivers")
    set_kind("shared")
    set_encodings("utf-8")
    add_defines("UNICODE", "NOMINMAX")
    add_files("src/victim-drivers/**.c", "src/victim-drivers/**.cpp", "src/victim-drivers/**.def", "src/victim-drivers/**.rc")
    add_headerfiles("src/victim-drivers/**.h", "src/victim-drivers/**.hpp")
    add_includedirs("src/victim-drivers", {public = true})
    add_deps("shared")
    set_languages("c11", "cxx17")

target("gen-asio-2-unlock")
    set_kind("binary")
    set_encodings("utf-8")
    add_defines("UNICODE", "NOMINMAX")
    add_files("src/utils/gen-asio-2-unlock/**.c", "src/utils/gen-asio-2-unlock/**.cpp")
    add_headerfiles("src/utils/gen-asio-2-unlock/**.h", "src/utils/gen-asio-2-unlock/**.hpp")
    add_includedirs("src/utils/gen-asio-2-unlock", {public = true})
    set_languages("c11", "cxx17")
    add_deps("shared")
    add_syslinks("advapi32")

-- target("PCOMP")
--     set_kind("binary")
--     set_encodings("utf-8")
--     add_files("src/utils/PCOMP/**.c", "src/utils/PCOMP/**.cpp")
--     add_headerfiles("src/utils/PCOMP/**.h", "src/utils/PCOMP/**.hpp")
--     add_includedirs("src/utils/PCOMP", {public = true})
--     set_languages("c11", "cxx11")
--     add_deps("shared")